name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci || npm install

      - name: Install Cypress
        run: npx cypress install

      - name: Fix Cypress permissions (just in case)
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress tests
        run: npx cypress run

      - name: Merge Mochawesome reports
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/output.json

      - name: Generate HTML report
        run: |
          npx marge cypress/reports/output.json -f report -o cypress/reports

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: Cypress-Test-Report
          path: cypress/reports/report.html
